#
# Kafka cluster definition
#
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: dale
spec:
  kafka:
    listeners:
      # internal service that the kafka-ml app will use
      plain: {}
      # external route for retrieving the predictions topic
      external:
        type: route
    config:
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    replicas: 3
    storage:
      type: ephemeral
    version: 2.5.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
