apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ml
  template:
    metadata:
      labels:
        app: kafka-ml
    spec:
      containers:
      - name: ml
        image: dalelane/kafka-ml:latest
        env:
        - name: KAFKA_BOOTSTRAP
          value: "dale-kafka-bootstrap:9092"
        - name: RAW_EVENTS_TOPIC
          value: "IPHONE.SENSORS"
        - name: PROCESSED_EVENTS_TOPIC
          value: "IPHONE.ACTIVITY"
